name: "Trybe Bootstrap Action"
author: "Trybe"
description: "Action utilizada para configurar o ambiente para executar a integração contínua das aplicações da Trybe."
inputs:
  environment:
    description: "Ambiente de destino da aplicação."
    required: true
  token:
    description: "Personal Acess Token para acessos a sistemas do GitHub."
    required: false

runs:
  using: "composite"
  steps:
    - id: job
      shell: bash
      run: ${{ github.action_path }}/bootstrap.sh
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        BOOTSTRAP_TOKEN: ${{ inputs.token }}
