name: "Trybe Image Builder"
author: "Trybe"
description: "Action utilizada para configurar o ambiente para executar a integração contínua das aplicações da Trybe."
inputs:
  environment:
    description: "Ambiente de destino da aplicação."
    required: true
  token:
    description: "Personal Acess Token para acessos a sistemas do GitHub."
    required: false
  githubToken:
    description: "Depreciado, não usar."
    required: false
  chartPrefix:
    description: "Prefixo para a localização das definições do Helm. É necessário incluir uma '/' no final do caminho"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - id: job
      shell: bash
      run: ${{ github.action_path }}/bootstrap.sh
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        BOOTSTRAP_TOKEN: ${{ inputs.token }}
        CHART_PREFIX: ${{ inputs.chartPrefix }}
